# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'finalsplash.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SplashWindow(object):
    def setupUi(self, SplashWindow):
        SplashWindow.setObjectName("SplashWindow")
        SplashWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(SplashWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.main_frame = QtWidgets.QFrame(self.centralwidget)
        self.main_frame.setStyleSheet("QFrame#main_frame{\n"
"\n"
"background-color:#2980b9;\n"
"color:white;\n"
"\n"
"}")
        self.main_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_frame.setObjectName("main_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.main_frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.top_frame = QtWidgets.QFrame(self.main_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.top_frame.sizePolicy().hasHeightForWidth())
        self.top_frame.setSizePolicy(sizePolicy)
        self.top_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.top_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top_frame.setObjectName("top_frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.top_frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.title_label = QtWidgets.QLabel(self.top_frame)
        font = QtGui.QFont()
        font.setFamily("Modern No. 20")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.title_label.setFont(font)
        self.title_label.setStyleSheet("QLabel#title_label{\n"
"color:white;\n"
"}")
        self.title_label.setAlignment(QtCore.Qt.AlignCenter)
        self.title_label.setObjectName("title_label")
        self.gridLayout_2.addWidget(self.title_label, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.top_frame)
        self.bottom_frame = QtWidgets.QFrame(self.main_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.bottom_frame.sizePolicy().hasHeightForWidth())
        self.bottom_frame.setSizePolicy(sizePolicy)
        self.bottom_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bottom_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bottom_frame.setObjectName("bottom_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.bottom_frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.videoPath_lineEdit = QtWidgets.QLineEdit(self.bottom_frame)
        self.videoPath_lineEdit.setStyleSheet("QLineEdit#videoPath_lineEdit{\n"
"  padding: 10 10;\n"
"  margin: 0 0;\n"
"  border: 1px solid #ccc;\n"
"  border-radius: 4px;\n"
"}\n"
"")
        self.videoPath_lineEdit.setReadOnly(True)
        self.videoPath_lineEdit.setObjectName("videoPath_lineEdit")
        self.horizontalLayout.addWidget(self.videoPath_lineEdit)
        self.choose_file_btn = QtWidgets.QPushButton(self.bottom_frame)
        self.choose_file_btn.setStyleSheet("QPushButton#choose_file_btn{\n"
"background-color:#9b59b6;\n"
"padding:30;\n"
"color:white;\n"
"border-radius:5;\n"
"}\n"
"QPushButton#choose_file_btn:hover{\n"
"background-color:#8e44ad;\n"
"}")
        self.choose_file_btn.setObjectName("choose_file_btn")
        self.horizontalLayout.addWidget(self.choose_file_btn, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.is_test_checkbox = QtWidgets.QCheckBox(self.bottom_frame)
        self.is_test_checkbox.setStyleSheet("QCheckBox{\n"
"color:white;\n"
"}")
        self.is_test_checkbox.setObjectName("is_test_checkbox")
        self.verticalLayout_2.addWidget(self.is_test_checkbox, 0, QtCore.Qt.AlignHCenter)
        self.continue_btn = QtWidgets.QPushButton(self.bottom_frame)
        self.continue_btn.setStyleSheet("QPushButton#continue_btn{\n"
"background-color:#badc58;\n"
"padding:30;\n"
"border-radius:5;\n"
"border:none;\n"
"}\n"
"QPushButton#continue_btn:hover{\n"
"background-color:#4cd137;\n"
"}")
        self.continue_btn.setObjectName("continue_btn")
        self.verticalLayout_2.addWidget(self.continue_btn, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout.addWidget(self.bottom_frame)
        self.gridLayout.addWidget(self.main_frame, 0, 0, 1, 1)
        SplashWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(SplashWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 20))
        self.menubar.setObjectName("menubar")
        SplashWindow.setMenuBar(self.menubar)

        self.retranslateUi(SplashWindow)
        QtCore.QMetaObject.connectSlotsByName(SplashWindow)

    def retranslateUi(self, SplashWindow):
        _translate = QtCore.QCoreApplication.translate
        SplashWindow.setWindowTitle(_translate("SplashWindow", "NSL"))
        self.title_label.setText(_translate("SplashWindow", "Nepali Sign Language Recognition System"))
        self.choose_file_btn.setText(_translate("SplashWindow", "Browse"))
        self.is_test_checkbox.setText(_translate("SplashWindow", "Is Test Video"))
        self.continue_btn.setText(_translate("SplashWindow", "Continue With Selected Options"))
